// Data & Analytics quotes for Stephen's farewell display
// Total: 130 quotes

static const char* quotes[] = {
  // Data & Analytics Wisdom
  "In God we trust. All others must bring data. - W. Edwards Deming",
  "Without data, you're just another person with an opinion. - W. Edwards Deming",
  "Data is the new oil. - Clive Humby",
  "The goal is to turn data into information, and information into insight. - Carly Fiorina",
  "Above all else, show the data. - Edward Tufte",
  "Statistics are the grammar of science. - Karl Pearson",
  "Data will talk if you listen. - Jim Bergeson",
  "Data beats emotions.",
  "Data is the language of business.",
  "Data is power.",

  // Machine Learning & AI
  "The best way to predict the future is to invent it. - Alan Kay",
  "AI is the new electricity. - Andrew Ng",
  "Machine learning is statistics on steroids.",
  "Big data is about talent, not size. - Douglas Merrill",
  "Data science is the sexiest job of the 21st century. - Davenport & Patil",
  "AI thrives on quality data.",
  "Machine learning learns patterns humans can't see.",
  "AI is only as good as its training data.",
  "Every model is wrong, some are useful. - George Box",
  "Data science is about asking better questions.",

  // Statistics & Probability
  "Torture the data and it will confess. - Ronald Coase",
  "Probability is common sense reduced to numbers. - Laplace",
  "Statistics make the invisible visible.",
  "Without uncertainty, no discovery.",
  "Randomness explains more than genius.",
  "Correlation does not imply causation.",
  "Noise hides signal.",
  "Sampling defines truth.",

  // Humorous
  "Data scientists spend 80% of their time cleaning data. - Josh Wills",
  "Garbage in, garbage out.",
  "If Excel can do it, it's not data science.",
  "Without coffee, no data science.",
  "Debugging is like detective work.",
  "Big data, bigger problems.",
  "Machine learning is magic, until it's not.",
  "If it works, don't touch it.",
  "First make it work, then make it fast.",
  "Simplicity scales.",

  // Business & Decision Making
  "Data-driven beats gut-driven.",
  "Decisions without data are guesses.",
  "Data is a strategic asset.",
  "Better data means better decisions.",
  "Measure what matters.",
  "Analytics turns hindsight into foresight.",
  "Numbers reduce bias.",
  "Strategy follows analytics.",
  "Trust the data, not the loudest voice.",
  "Business runs on insights.",

  // Data Science Philosophy
  "Data science is storytelling.",
  "Every dataset tells a story.",
  "Data science is curiosity plus computation.",
  "Good models explain, not just predict.",
  "Insight beats information.",
  "Data reveals truth.",
  "Models amplify understanding.",
  "Algorithms shape reality.",
  "Data is human behavior in numbers.",
  "Data science is a way of thinking.",

  // Coding, Modeling & Engineering
  "Clean code beats clever code.",
  "Code is communication.",
  "Debugging builds mastery.",
  "Pipelines matter more than models.",
  "Reproducibility is non-negotiable.",
  "Automation multiplies intelligence.",
  "Complex models hide bugs.",
  "Models reflect assumptions.",
  "Simple models generalize better.",
  "Infrastructure is destiny.",

  // Big Data & Scalability
  "Big data means big responsibility.",
  "More data beats smarter algorithms.",
  "Storage is cheap, insight is expensive.",
  "Scale changes everything.",
  "Data volume is meaningless without value.",
  "Big data reveals macro patterns.",
  "Small data reveals micro truths.",
  "Size amplifies errors.",
  "Speed wins markets.",
  "Scale exposes flaws.",

  // Ethics, Bias & Fairness
  "Bias in data creates bias in models.",
  "Fair data builds fair AI.",
  "Transparency builds trust.",
  "Ethics is part of engineering.",
  "Algorithms reflect their creators.",
  "Explainability matters.",
  "Data privacy is fundamental.",
  "Responsible AI is essential.",
  "Fairness must be engineered.",
  "Trust is built through clarity.",

  // Learning & Growth
  "Learn data by doing.",
  "Curiosity drives discovery.",
  "Practice builds intuition.",
  "Failure teaches more than success.",
  "Continuous learning is mandatory.",
  "Data science rewards persistence.",
  "Mastery comes from repetition.",
  "Questions drive progress.",
  "Knowledge compounds.",
  "Learning never stops.",

  // Prediction & Forecasting
  "Forecasting is educated guessing.",
  "Prediction is probability in action.",
  "Uncertainty is unavoidable.",
  "Good forecasts guide action.",
  "Overfitting kills accuracy.",
  "Validation prevents illusion.",
  "Models predict trends, not certainties.",
  "Confidence intervals matter.",
  "Testing builds trust.",
  "All models simplify reality.",

  // Visualization & Communication
  "Charts speak louder than numbers.",
  "Good visuals tell stories.",
  "Simplicity beats complexity.",
  "Clarity drives insight.",
  "Bad charts mislead.",
  "Design improves comprehension.",
  "Visuals amplify understanding.",
  "Context gives meaning.",
  "Data deserves good design.",

  // Advanced AI Thinking
  "Intelligence emerges from patterns.",
  "AI extends human capability.",
  "Algorithms mimic reasoning.",
  "Neural networks emulate brains.",
  "Computation fuels intelligence.",
  "AI accelerates innovation.",
  "Models simulate intelligence.",
  "Learning machines mirror cognition.",
  "Intelligence is optimization.",
  "AI learns from experience.",

  // Problem Solving
  "Better questions create better answers.",
  "Problems define solutions.",
  "Exploration precedes prediction.",
  "Insight follows curiosity.",
  "Thinking beats tooling.",
  "Frameworks guide reasoning.",
  "Logic drives models.",
  "Patterns explain chaos.",
  "Structure reveals clarity.",
  "Reason before code.",

  // Career & Growth
  "Skills outlive tools.",
  "Learning beats credentials.",
  "Consistency wins.",
  "Patience builds excellence.",
  "Discipline drives results.",
  "Failure teaches resilience.",
  "Persistence beats talent.",
  "Curiosity creates experts.",
  "Growth compounds.",
  "Excellence is a habit.",
};
